### PR TITLE
Switch to jbuilder

### PR DESCRIPTION
**Pull request by samoht**
I haven't ported the examples to jbuilder yet, let me know if this is needed. The main missing thing is setting up the right dependencies in the opam files (currently they are just copy/pasted from the initial one -- this is clearly wrong).

Also, I haven't been able to run the tests as I am not sure which db should I use and how to configure it. But the tests are compiling so I guess that's fine :-)

This PR also removes the optional dependencies and introduces the following opam packages:

- session
- session-redis-lwt
- session-postgresql
- session-postgresql-lwt
- session-postgresql-async
- session-cohttp
- session-cohttp-lwt
- session-cohttp-async
- session-webmachine

### CODE REVIEW

**Comment by samoht** [comment]
I have fixed the opam files, added a target to compile the examples (they now compile without warnings) and updated the Travis scripts to tests all the new packages. I think that PR is ready to merge.

**Comment by seliopou** [comment]
Thanks for this. I'll take a look later this evening.

**Comment by seliopou** [comment]
Thanks!

**Comment by samoht** [comment]
Would it be possible to make a new release with these changes? Thanks!

**Comment by seliopou** [comment]
Yup I'll give it a go in between sessions.

**Pull request merged**
