### PR TITLE
Add Redis backend

### LINKED ISSUE #3: Implement Redis backend
Hi,

There's [OCaml Redis client library](https://github.com/0xffea/ocaml-redis), so it would be trivial to add Redis backend for sessions.

### PR DESCRIPTION
**Pull request by talex5**
Notes:

- The test code checks that it gets "Expired" for expired keys. But keeping expired keys around seems pointless, so for the Redis checks I allow it to return Not_found instead.

- The tests assume you have a Redis server running on 127.0.0.1, which probably isn't reasonable. Maybe they should be disabled. How does it work for Postgres?

Fixes #3.

Has only been *very* lightly tested so far.

### CODE REVIEW

**Comment by talex5** [comment]
A few updates:

- I've added a new flag to enable the Redis tests: `./configure --enable-redis-tests`.
- I use a connection pool rather than a single connection, so it can recover if the connection is lost and can run queries in parallel.
- Added a prefix to the session keys in case the DB is being used for other things too.

**Comment by talex5** [comment]
We've been using this for a few weeks now and it seems to be working well.

**Comment by talex5** [comment]
Would be good to get this merged, because it's a dependency of datakit-ci and we can't release that to opam-repository until this is released.

**Comment by avsm** [comment]
Thanks for merging! Any chance of a release in opam-repository stable containing this, so that we can release the CI software as well?

**Comment by seliopou** [comment]
See ocaml/opam-repository#8374

**Comment by talex5** [comment]
Thanks! I've updated DataKitCI to use the released version.

**Comment by avsm** [comment]
thanks @seliopou!

**Pull request merged**
